# docker-compose -f docker-compose.yml -f docker-compose.override.yml up -d    
version: '3.4'

services:
  mongo:
    image: mongo

  redis:
    image: redis:alpine

  pgadmin:
    image: dpage/pgadmin4

  postgres:
    image: postgres

  storage:
    image: mcr.microsoft.com/azure-storage/azurite

  rabbitmq:
    image: rabbitmq:3-management

  sql-server:
    image: mcr.microsoft.com/mssql/server:2017-latest

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.9.2

  kibana:
    image: docker.elastic.co/kibana/kibana:7.9.2

volumes:
  mongo_data:
  postgres_data:
  pgadmin_data:
  elasticsearch-data: